### ISSUE TITLE
Hora incorrecta en los mensajes con la información de la parada

### ISSUE THREAD

**Issue by ManuLG** [dpeite/VitrasaTelegramBot#3]
Tanto cuando se envía un mensaje para obtener la información de una nueva parada como cuando se actualiza uno ya existente la hora no se corresponde con la del dispositivo.

![image 2018-03-22 11 29 56](https://user-images.githubusercontent.com/16776395/37765415-59d6513e-2dc4-11e8-9f87-a4af64412ce1.jpg)

**Comment by dpeite** [comment]
Solucionado en https://github.com/dpeite/VitrasaTelegramBot/commit/d931a388e0db350212d641dc5aa380cb0e9b81cc
